#!/usr/bin/env bash
# gen-checks-docs.sh — regenerate docs/checks/<ID>.md from the live catalog.
#
# Usage:
#   scripts/gen-checks-docs.sh                     # standalone, default
#   scripts/gen-checks-docs.sh --server URL        # hit a running websec0
#   WEBSEC0_API_KEY=… scripts/gen-checks-docs.sh --server https://…
#
# The script is idempotent: it wipes docs/checks/*.md before writing.
# The index docs/checks/README.md is regenerated too.
#
# Requires: jq, and either the `websec0-cli` binary on $PATH or `go run`.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/docs/checks"
SERVER=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server) SERVER="$2"; shift 2 ;;
    --help|-h)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

command -v jq >/dev/null 2>&1 || { echo "jq is required" >&2; exit 1; }

mkdir -p "$OUT_DIR"
find "$OUT_DIR" -maxdepth 1 -type f -name '*.md' -delete

# Fetch the catalog as JSON.
catalog_json="$(mktemp)"
trap 'rm -f "$catalog_json"' EXIT

if [[ -n "$SERVER" ]]; then
  auth=()
  if [[ -n "${WEBSEC0_API_KEY:-}" ]]; then
    auth=(-H "Authorization: Bearer $WEBSEC0_API_KEY")
  fi
  curl -sSf "${auth[@]}" "$SERVER/api/v1/checks" > "$catalog_json"
else
  if command -v websec0-cli >/dev/null 2>&1; then
    websec0-cli catalog --standalone --json > "$catalog_json"
  else
    (cd "$ROOT" && go run ./cmd/websec0-cli catalog --standalone --json) > "$catalog_json"
  fi
fi

count="$(jq 'length' "$catalog_json")"
echo "Found $count checks; writing $OUT_DIR/"

# One Markdown file per check.
jq -c '.[]' "$catalog_json" | while read -r entry; do
  id=$(jq -r '.id' <<<"$entry")
  family=$(jq -r '.family' <<<"$entry")
  severity=$(jq -r '.default_severity' <<<"$entry")
  title=$(jq -r '.title // ""' <<<"$entry")
  desc=$(jq -r '.description // ""' <<<"$entry")
  rfcs=$(jq -r '.rfc_refs // [] | join(", ")' <<<"$entry")

  file="$OUT_DIR/$id.md"
  {
    echo "# $id"
    echo
    if [[ -n "$title" ]]; then echo "**$title**"; echo; fi
    echo "| Field | Value |"
    echo "|---|---|"
    echo "| ID | \`$id\` |"
    echo "| Family | \`$family\` |"
    echo "| Default severity | \`$severity\` |"
    if [[ -n "$rfcs" ]]; then echo "| References | $rfcs |"; fi
    echo
    if [[ -n "$desc" ]]; then
      echo "## Description"
      echo
      echo "$desc"
      echo
    fi
    echo "## Live catalog entry"
    echo
    echo "Stable, machine-readable metadata is served by"
    echo "\`GET /api/v1/checks/$id\`. Re-fetch for the authoritative version:"
    echo
    echo "\`\`\`bash"
    echo "curl -s https://websec0.example/api/v1/checks/$id | jq"
    echo "\`\`\`"
    echo
    echo "## See also"
    echo
    echo "- [Checks index](./README.md)"
    echo "- [Family: $family](./README.md#family-$family)"
    echo "- [SPECIFICATIONS §3 — Catalogue des checks](../../SPECIFICATIONS.md#3-catalogue-des-checks)"
    echo
    echo "<!-- Generated by scripts/gen-checks-docs.sh — do not edit by hand. -->"
  } > "$file"
done

# Index page grouped by family.
{
  echo "# Checks catalog"
  echo
  echo "$count checks across 7 families. Generated from \`GET /api/v1/checks\`"
  echo "by \`scripts/gen-checks-docs.sh\`. The live catalog is the source of truth."
  echo
  echo "> Run \`scripts/gen-checks-docs.sh\` after adding or modifying a check"
  echo "> to refresh this directory."
  echo
  echo "## By family"
  echo
  jq -r '[.[].family] | unique | .[]' "$catalog_json" | while read -r fam; do
    fam_count=$(jq --arg f "$fam" '[.[] | select(.family == $f)] | length' "$catalog_json")
    echo "### Family: $fam"
    echo
    echo "$fam_count checks."
    echo
    echo "| ID | Severity | Title |"
    echo "|---|---|---|"
    jq -r --arg f "$fam" '
      [.[] | select(.family == $f)]
      | sort_by(.id)
      | .[]
      | "| [\(.id)](./\(.id).md) | `\(.default_severity)` | \(.title // "") |"
    ' "$catalog_json"
    echo
  done
  echo "<!-- Generated by scripts/gen-checks-docs.sh — do not edit by hand. -->"
} > "$OUT_DIR/README.md"

echo "Wrote $OUT_DIR/README.md and $count check files."
