// Package handlers implements the WebSec101 OpenAPI server interface
// generated by ogen. At Phase 3, only health/version/openapi are
// real — the rest delegates to client.UnimplementedHandler and returns
// 501 via the configured error handler.
package handlers

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	ogenhttp "github.com/ogen-go/ogen/http"
	ogenerrors "github.com/ogen-go/ogen/ogenerrors"

	"github.com/Jomar/websec101/internal/api/spec"
	"github.com/Jomar/websec101/internal/checks"
	"github.com/Jomar/websec101/internal/scanner/safety"
	"github.com/Jomar/websec101/internal/storage"
	"github.com/Jomar/websec101/internal/version"
	client "github.com/Jomar/websec101/pkg/client"
)

// Handler is the concrete ogen Handler implementation.
//
// The embedded UnimplementedHandler causes any method we do not override
// to return ht.ErrNotImplemented, which the configured error handler
// translates to HTTP 501.
type Handler struct {
	client.UnimplementedHandler

	store          storage.ScanStore
	registry       *checks.Registry
	scans          ScanService
	policy         *safety.Policy
	perScanTimeout time.Duration
	startedAt      time.Time
}

// Options aggregates the dependencies of a Handler.
type Options struct {
	Store          storage.ScanStore
	Registry       *checks.Registry
	Scans          ScanService
	Policy         *safety.Policy
	PerScanTimeout time.Duration
}

// New constructs a Handler.
func New(opts Options) *Handler {
	if opts.PerScanTimeout <= 0 {
		opts.PerScanTimeout = 120 * time.Second
	}
	if opts.Policy == nil {
		opts.Policy = safety.Default()
	}
	return &Handler{
		store:          opts.Store,
		registry:       opts.Registry,
		scans:          opts.Scans,
		policy:         opts.Policy,
		perScanTimeout: opts.PerScanTimeout,
		startedAt:      time.Now(),
	}
}

// GetHealth implements GET /api/v1/health.
func (h *Handler) GetHealth(_ context.Context) (*client.Health, error) {
	uptime := int64(time.Since(h.startedAt).Seconds())
	return &client.Health{
		Status:        client.HealthStatusOk,
		UptimeSeconds: uptime,
		Version:       version.Version,
	}, nil
}

// GetVersion implements GET /api/v1/version.
func (h *Handler) GetVersion(_ context.Context) (*client.Version, error) {
	info := version.Get()
	return &client.Version{
		Version:   info.Version,
		Commit:    info.Commit,
		BuildDate: info.BuildDate,
	}, nil
}

// GetOpenAPI implements GET /api/v1/openapi.json.
func (h *Handler) GetOpenAPI(_ context.Context) (client.GetOpenAPIOK, error) {
	m, err := spec.AsRawMap()
	if err != nil {
		return nil, fmt.Errorf("openapi: %w", err)
	}
	out := make(client.GetOpenAPIOK, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out, nil
}

// ErrorHandler maps handler-returned errors to JSON envelopes. ogen's
// UnimplementedHandler returns ht.ErrNotImplemented; we surface that as
// 501. Decode failures (typed by ogenerrors) become 400. Anything else
// is a 500.
func ErrorHandler(_ context.Context, w http.ResponseWriter, _ *http.Request, err error) {
	w.Header().Set("Content-Type", "application/json")

	status := http.StatusInternalServerError
	code := "internal_error"
	switch {
	case errors.Is(err, ogenhttp.ErrNotImplemented):
		status = http.StatusNotImplemented
		code = "not_implemented"
	case isDecodeError(err):
		status = http.StatusBadRequest
		code = "bad_request"
	}

	w.WriteHeader(status)
	body := fmt.Sprintf(`{"code":%q,"message":%q}`, code, err.Error())
	_, _ = w.Write([]byte(body))
}

func isDecodeError(err error) bool {
	var de *ogenerrors.DecodeRequestError
	if errors.As(err, &de) {
		return true
	}
	var pe *ogenerrors.DecodeParamsError
	return errors.As(err, &pe)
}
