// Code generated by ogen, DO NOT EDIT.

package client

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateScanOperation      OperationName = "CreateScan"
	DeleteScanOperation      OperationName = "DeleteScan"
	GetCheckOperation        OperationName = "GetCheck"
	GetHealthOperation       OperationName = "GetHealth"
	GetOpenAPIOperation      OperationName = "GetOpenAPI"
	GetScanOperation         OperationName = "GetScan"
	GetScanMarkdownOperation OperationName = "GetScanMarkdown"
	GetScanSARIFOperation    OperationName = "GetScanSARIF"
	GetVersionOperation      OperationName = "GetVersion"
	ListChecksOperation      OperationName = "ListChecks"
)
