// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *ScanOptions) setDefaults() {
	{
		val := bool(false)
		s.Private.SetTo(val)
	}
	{
		val := int(0)
		s.WaitSeconds.SetTo(val)
	}
}
