// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateScan implements createScan operation.
	//
	// Always returns 202 with a freshly minted GUIDv4 and a `Location`
	// header. Use `options.wait_seconds` for short synchronous waits.
	//
	// POST /api/v1/scans
	CreateScan(ctx context.Context, req *ScanRequest) (CreateScanRes, error)
	// DeleteScan implements deleteScan operation.
	//
	// Delete a scan (private mode requires token).
	//
	// DELETE /api/v1/scans/{guid}
	DeleteScan(ctx context.Context, params DeleteScanParams) (DeleteScanRes, error)
	// GetCheck implements getCheck operation.
	//
	// Fetch a single check definition.
	//
	// GET /api/v1/checks/{check_id}
	GetCheck(ctx context.Context, params GetCheckParams) (GetCheckRes, error)
	// GetHealth implements getHealth operation.
	//
	// Liveness/health probe.
	//
	// GET /api/v1/health
	GetHealth(ctx context.Context) (*Health, error)
	// GetInstance implements getInstance operation.
	//
	// Returns the contact email and User-Agent string the operator has
	// configured for this instance. The frontend reads this endpoint to
	// render legal / about pages without baking deployment-specific
	// values into the embedded HTML.
	//
	// GET /api/v1/instance
	GetInstance(ctx context.Context) (*Instance, error)
	// GetOpenAPI implements getOpenAPI operation.
	//
	// Embedded OpenAPI 3.0 specification.
	//
	// GET /api/v1/openapi.json
	GetOpenAPI(ctx context.Context) (GetOpenAPIOK, error)
	// GetScan implements getScan operation.
	//
	// Fetch a scan (always 200).
	//
	// GET /api/v1/scans/{guid}
	GetScan(ctx context.Context, params GetScanParams) (GetScanRes, error)
	// GetScanMarkdown implements getScanMarkdown operation.
	//
	// Markdown report.
	//
	// GET /api/v1/scans/{guid}/markdown
	GetScanMarkdown(ctx context.Context, params GetScanMarkdownParams) (GetScanMarkdownRes, error)
	// GetScanSARIF implements getScanSARIF operation.
	//
	// SARIF 2.1.0 report.
	//
	// GET /api/v1/scans/{guid}/sarif
	GetScanSARIF(ctx context.Context, params GetScanSARIFParams) (GetScanSARIFRes, error)
	// GetVersion implements getVersion operation.
	//
	// Build metadata.
	//
	// GET /api/v1/version
	GetVersion(ctx context.Context) (*Version, error)
	// ListChecks implements listChecks operation.
	//
	// List all supported checks.
	//
	// GET /api/v1/checks
	ListChecks(ctx context.Context) ([]Check, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
