// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateScan implements createScan operation.
//
// Always returns 202 with a freshly minted GUIDv4 and a `Location`
// header. Use `options.wait_seconds` for short synchronous waits.
//
// POST /api/v1/scans
func (UnimplementedHandler) CreateScan(ctx context.Context, req *ScanRequest) (r CreateScanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteScan implements deleteScan operation.
//
// Delete a scan (private mode requires token).
//
// DELETE /api/v1/scans/{guid}
func (UnimplementedHandler) DeleteScan(ctx context.Context, params DeleteScanParams) (r DeleteScanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCheck implements getCheck operation.
//
// Fetch a single check definition.
//
// GET /api/v1/checks/{check_id}
func (UnimplementedHandler) GetCheck(ctx context.Context, params GetCheckParams) (r GetCheckRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Liveness/health probe.
//
// GET /api/v1/health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInstance implements getInstance operation.
//
// Returns the contact email and User-Agent string the operator has
// configured for this instance. The frontend reads this endpoint to
// render legal / about pages without baking deployment-specific
// values into the embedded HTML.
//
// GET /api/v1/instance
func (UnimplementedHandler) GetInstance(ctx context.Context) (r *Instance, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOpenAPI implements getOpenAPI operation.
//
// Embedded OpenAPI 3.0 specification.
//
// GET /api/v1/openapi.json
func (UnimplementedHandler) GetOpenAPI(ctx context.Context) (r GetOpenAPIOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetScan implements getScan operation.
//
// Fetch a scan (always 200).
//
// GET /api/v1/scans/{guid}
func (UnimplementedHandler) GetScan(ctx context.Context, params GetScanParams) (r GetScanRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetScanMarkdown implements getScanMarkdown operation.
//
// Markdown report.
//
// GET /api/v1/scans/{guid}/markdown
func (UnimplementedHandler) GetScanMarkdown(ctx context.Context, params GetScanMarkdownParams) (r GetScanMarkdownRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetScanSARIF implements getScanSARIF operation.
//
// SARIF 2.1.0 report.
//
// GET /api/v1/scans/{guid}/sarif
func (UnimplementedHandler) GetScanSARIF(ctx context.Context, params GetScanSARIFParams) (r GetScanSARIFRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetVersion implements getVersion operation.
//
// Build metadata.
//
// GET /api/v1/version
func (UnimplementedHandler) GetVersion(ctx context.Context) (r *Version, _ error) {
	return r, ht.ErrNotImplemented
}

// ListChecks implements listChecks operation.
//
// List all supported checks.
//
// GET /api/v1/checks
func (UnimplementedHandler) ListChecks(ctx context.Context) (r []Check, _ error) {
	return r, ht.ErrNotImplemented
}
