// Code generated by ogen, DO NOT EDIT.

package client

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteScanParams is parameters of deleteScan operation.
type DeleteScanParams struct {
	// GUIDv4 of the scan.
	GUID uuid.UUID
}

func unpackDeleteScanParams(packed middleware.Parameters) (params DeleteScanParams) {
	{
		key := middleware.ParameterKey{
			Name: "guid",
			In:   "path",
		}
		params.GUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteScanParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteScanParams, _ error) {
	// Decode path: guid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "guid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "guid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetCheckParams is parameters of getCheck operation.
type GetCheckParams struct {
	// Stable check identifier (SCREAMING-KEBAB-CASE).
	CheckID string
}

func unpackGetCheckParams(packed middleware.Parameters) (params GetCheckParams) {
	{
		key := middleware.ParameterKey{
			Name: "check_id",
			In:   "path",
		}
		params.CheckID = packed[key].(string)
	}
	return params
}

func decodeGetCheckParams(args [1]string, argsEscaped bool, r *http.Request) (params GetCheckParams, _ error) {
	// Decode path: check_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "check_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CheckID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "check_id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetScanParams is parameters of getScan operation.
type GetScanParams struct {
	// GUIDv4 of the scan.
	GUID uuid.UUID
}

func unpackGetScanParams(packed middleware.Parameters) (params GetScanParams) {
	{
		key := middleware.ParameterKey{
			Name: "guid",
			In:   "path",
		}
		params.GUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetScanParams(args [1]string, argsEscaped bool, r *http.Request) (params GetScanParams, _ error) {
	// Decode path: guid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "guid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "guid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetScanMarkdownParams is parameters of getScanMarkdown operation.
type GetScanMarkdownParams struct {
	// GUIDv4 of the scan.
	GUID uuid.UUID
}

func unpackGetScanMarkdownParams(packed middleware.Parameters) (params GetScanMarkdownParams) {
	{
		key := middleware.ParameterKey{
			Name: "guid",
			In:   "path",
		}
		params.GUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetScanMarkdownParams(args [1]string, argsEscaped bool, r *http.Request) (params GetScanMarkdownParams, _ error) {
	// Decode path: guid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "guid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "guid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetScanSARIFParams is parameters of getScanSARIF operation.
type GetScanSARIFParams struct {
	// GUIDv4 of the scan.
	GUID uuid.UUID
}

func unpackGetScanSARIFParams(packed middleware.Parameters) (params GetScanSARIFParams) {
	{
		key := middleware.ParameterKey{
			Name: "guid",
			In:   "path",
		}
		params.GUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetScanSARIFParams(args [1]string, argsEscaped bool, r *http.Request) (params GetScanSARIFParams, _ error) {
	// Decode path: guid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "guid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.GUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "guid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
