// Code generated by ogen, DO NOT EDIT.
package client

type CreateScanRes interface {
	createScanRes()
}

type DeleteScanRes interface {
	deleteScanRes()
}

type GetCheckRes interface {
	getCheckRes()
}

type GetScanMarkdownRes interface {
	getScanMarkdownRes()
}

type GetScanRes interface {
	getScanRes()
}

type GetScanSARIFRes interface {
	getScanSARIFRes()
}
