// Code generated by ogen, DO NOT EDIT.

package client

import (
	"io"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/Check
type Check struct {
	ID              string    `json:"id"`
	Family          string    `json:"family"`
	DefaultSeverity Severity  `json:"default_severity"`
	Title           OptString `json:"title"`
	Description     OptString `json:"description"`
	RfcRefs         []string  `json:"rfc_refs"`
}

// GetID returns the value of ID.
func (s *Check) GetID() string {
	return s.ID
}

// GetFamily returns the value of Family.
func (s *Check) GetFamily() string {
	return s.Family
}

// GetDefaultSeverity returns the value of DefaultSeverity.
func (s *Check) GetDefaultSeverity() Severity {
	return s.DefaultSeverity
}

// GetTitle returns the value of Title.
func (s *Check) GetTitle() OptString {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Check) GetDescription() OptString {
	return s.Description
}

// GetRfcRefs returns the value of RfcRefs.
func (s *Check) GetRfcRefs() []string {
	return s.RfcRefs
}

// SetID sets the value of ID.
func (s *Check) SetID(val string) {
	s.ID = val
}

// SetFamily sets the value of Family.
func (s *Check) SetFamily(val string) {
	s.Family = val
}

// SetDefaultSeverity sets the value of DefaultSeverity.
func (s *Check) SetDefaultSeverity(val Severity) {
	s.DefaultSeverity = val
}

// SetTitle sets the value of Title.
func (s *Check) SetTitle(val OptString) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Check) SetDescription(val OptString) {
	s.Description = val
}

// SetRfcRefs sets the value of RfcRefs.
func (s *Check) SetRfcRefs(val []string) {
	s.RfcRefs = val
}

func (*Check) getCheckRes() {}

// DeleteScanNoContent is response for DeleteScan operation.
type DeleteScanNoContent struct{}

func (*DeleteScanNoContent) deleteScanRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Details OptErrorDetails `json:"details"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Error) GetDetails() OptErrorDetails {
	return s.Details
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Error) SetDetails(val OptErrorDetails) {
	s.Details = val
}

type ErrorDetails map[string]jx.Raw

func (s *ErrorDetails) init() ErrorDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

func (*ErrorStatusCode) createScanRes()      {}
func (*ErrorStatusCode) deleteScanRes()      {}
func (*ErrorStatusCode) getCheckRes()        {}
func (*ErrorStatusCode) getScanMarkdownRes() {}
func (*ErrorStatusCode) getScanRes()         {}
func (*ErrorStatusCode) getScanSARIFRes()    {}

// Ref: #/components/schemas/Finding
type Finding struct {
	ID          string                `json:"id"`
	Family      string                `json:"family"`
	Severity    Severity              `json:"severity"`
	Status      FindingStatus         `json:"status"`
	Title       OptString             `json:"title"`
	Description OptString             `json:"description"`
	Evidence    OptFindingEvidence    `json:"evidence"`
	Remediation OptFindingRemediation `json:"remediation"`
}

// GetID returns the value of ID.
func (s *Finding) GetID() string {
	return s.ID
}

// GetFamily returns the value of Family.
func (s *Finding) GetFamily() string {
	return s.Family
}

// GetSeverity returns the value of Severity.
func (s *Finding) GetSeverity() Severity {
	return s.Severity
}

// GetStatus returns the value of Status.
func (s *Finding) GetStatus() FindingStatus {
	return s.Status
}

// GetTitle returns the value of Title.
func (s *Finding) GetTitle() OptString {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Finding) GetDescription() OptString {
	return s.Description
}

// GetEvidence returns the value of Evidence.
func (s *Finding) GetEvidence() OptFindingEvidence {
	return s.Evidence
}

// GetRemediation returns the value of Remediation.
func (s *Finding) GetRemediation() OptFindingRemediation {
	return s.Remediation
}

// SetID sets the value of ID.
func (s *Finding) SetID(val string) {
	s.ID = val
}

// SetFamily sets the value of Family.
func (s *Finding) SetFamily(val string) {
	s.Family = val
}

// SetSeverity sets the value of Severity.
func (s *Finding) SetSeverity(val Severity) {
	s.Severity = val
}

// SetStatus sets the value of Status.
func (s *Finding) SetStatus(val FindingStatus) {
	s.Status = val
}

// SetTitle sets the value of Title.
func (s *Finding) SetTitle(val OptString) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Finding) SetDescription(val OptString) {
	s.Description = val
}

// SetEvidence sets the value of Evidence.
func (s *Finding) SetEvidence(val OptFindingEvidence) {
	s.Evidence = val
}

// SetRemediation sets the value of Remediation.
func (s *Finding) SetRemediation(val OptFindingRemediation) {
	s.Remediation = val
}

type FindingEvidence map[string]jx.Raw

func (s *FindingEvidence) init() FindingEvidence {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type FindingRemediation map[string]jx.Raw

func (s *FindingRemediation) init() FindingRemediation {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/FindingStatus
type FindingStatus string

const (
	FindingStatusPass    FindingStatus = "pass"
	FindingStatusFail    FindingStatus = "fail"
	FindingStatusWarn    FindingStatus = "warn"
	FindingStatusError   FindingStatus = "error"
	FindingStatusSkipped FindingStatus = "skipped"
)

// AllValues returns all FindingStatus values.
func (FindingStatus) AllValues() []FindingStatus {
	return []FindingStatus{
		FindingStatusPass,
		FindingStatusFail,
		FindingStatusWarn,
		FindingStatusError,
		FindingStatusSkipped,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s FindingStatus) MarshalText() ([]byte, error) {
	switch s {
	case FindingStatusPass:
		return []byte(s), nil
	case FindingStatusFail:
		return []byte(s), nil
	case FindingStatusWarn:
		return []byte(s), nil
	case FindingStatusError:
		return []byte(s), nil
	case FindingStatusSkipped:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *FindingStatus) UnmarshalText(data []byte) error {
	switch FindingStatus(data) {
	case FindingStatusPass:
		*s = FindingStatusPass
		return nil
	case FindingStatusFail:
		*s = FindingStatusFail
		return nil
	case FindingStatusWarn:
		*s = FindingStatusWarn
		return nil
	case FindingStatusError:
		*s = FindingStatusError
		return nil
	case FindingStatusSkipped:
		*s = FindingStatusSkipped
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetOpenAPIOK map[string]jx.Raw

func (s *GetOpenAPIOK) init() GetOpenAPIOK {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type GetScanMarkdownOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s GetScanMarkdownOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*GetScanMarkdownOK) getScanMarkdownRes() {}

type GetScanSARIFOK map[string]jx.Raw

func (s *GetScanSARIFOK) init() GetScanSARIFOK {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

func (*GetScanSARIFOK) getScanSARIFRes() {}

// Ref: #/components/schemas/Health
type Health struct {
	Status        HealthStatus `json:"status"`
	UptimeSeconds int64        `json:"uptime_seconds"`
	Version       string       `json:"version"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// GetUptimeSeconds returns the value of UptimeSeconds.
func (s *Health) GetUptimeSeconds() int64 {
	return s.UptimeSeconds
}

// GetVersion returns the value of Version.
func (s *Health) GetVersion() string {
	return s.Version
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

// SetUptimeSeconds sets the value of UptimeSeconds.
func (s *Health) SetUptimeSeconds(val int64) {
	s.UptimeSeconds = val
}

// SetVersion sets the value of Version.
func (s *Health) SetVersion(val string) {
	s.Version = val
}

type HealthStatus string

const (
	HealthStatusOk HealthStatus = "ok"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorDetails returns new OptErrorDetails with value set to v.
func NewOptErrorDetails(v ErrorDetails) OptErrorDetails {
	return OptErrorDetails{
		Value: v,
		Set:   true,
	}
}

// OptErrorDetails is optional ErrorDetails.
type OptErrorDetails struct {
	Value ErrorDetails
	Set   bool
}

// IsSet returns true if OptErrorDetails was set.
func (o OptErrorDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorDetails) Reset() {
	var v ErrorDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorDetails) SetTo(v ErrorDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorDetails) Get() (v ErrorDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorDetails) Or(d ErrorDetails) ErrorDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFindingEvidence returns new OptFindingEvidence with value set to v.
func NewOptFindingEvidence(v FindingEvidence) OptFindingEvidence {
	return OptFindingEvidence{
		Value: v,
		Set:   true,
	}
}

// OptFindingEvidence is optional FindingEvidence.
type OptFindingEvidence struct {
	Value FindingEvidence
	Set   bool
}

// IsSet returns true if OptFindingEvidence was set.
func (o OptFindingEvidence) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFindingEvidence) Reset() {
	var v FindingEvidence
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFindingEvidence) SetTo(v FindingEvidence) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFindingEvidence) Get() (v FindingEvidence, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFindingEvidence) Or(d FindingEvidence) FindingEvidence {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFindingRemediation returns new OptFindingRemediation with value set to v.
func NewOptFindingRemediation(v FindingRemediation) OptFindingRemediation {
	return OptFindingRemediation{
		Value: v,
		Set:   true,
	}
}

// OptFindingRemediation is optional FindingRemediation.
type OptFindingRemediation struct {
	Value FindingRemediation
	Set   bool
}

// IsSet returns true if OptFindingRemediation was set.
func (o OptFindingRemediation) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFindingRemediation) Reset() {
	var v FindingRemediation
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFindingRemediation) SetTo(v FindingRemediation) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFindingRemediation) Get() (v FindingRemediation, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFindingRemediation) Or(d FindingRemediation) FindingRemediation {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProgress returns new OptProgress with value set to v.
func NewOptProgress(v Progress) OptProgress {
	return OptProgress{
		Value: v,
		Set:   true,
	}
}

// OptProgress is optional Progress.
type OptProgress struct {
	Value Progress
	Set   bool
}

// IsSet returns true if OptProgress was set.
func (o OptProgress) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProgress) Reset() {
	var v Progress
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProgress) SetTo(v Progress) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProgress) Get() (v Progress, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProgress) Or(d Progress) Progress {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptScanOptions returns new OptScanOptions with value set to v.
func NewOptScanOptions(v ScanOptions) OptScanOptions {
	return OptScanOptions{
		Value: v,
		Set:   true,
	}
}

// OptScanOptions is optional ScanOptions.
type OptScanOptions struct {
	Value ScanOptions
	Set   bool
}

// IsSet returns true if OptScanOptions was set.
func (o OptScanOptions) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptScanOptions) Reset() {
	var v ScanOptions
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptScanOptions) SetTo(v ScanOptions) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptScanOptions) Get() (v ScanOptions, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptScanOptions) Or(d ScanOptions) ScanOptions {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Progress
type Progress struct {
	Total        int       `json:"total"`
	Completed    int       `json:"completed"`
	CurrentPhase OptString `json:"current_phase"`
}

// GetTotal returns the value of Total.
func (s *Progress) GetTotal() int {
	return s.Total
}

// GetCompleted returns the value of Completed.
func (s *Progress) GetCompleted() int {
	return s.Completed
}

// GetCurrentPhase returns the value of CurrentPhase.
func (s *Progress) GetCurrentPhase() OptString {
	return s.CurrentPhase
}

// SetTotal sets the value of Total.
func (s *Progress) SetTotal(val int) {
	s.Total = val
}

// SetCompleted sets the value of Completed.
func (s *Progress) SetCompleted(val int) {
	s.Completed = val
}

// SetCurrentPhase sets the value of CurrentPhase.
func (s *Progress) SetCurrentPhase(val OptString) {
	s.CurrentPhase = val
}

// Ref: #/components/schemas/Scan
type Scan struct {
	ID          uuid.UUID   `json:"id"`
	Status      ScanStatus  `json:"status"`
	Target      string      `json:"target"`
	StartedAt   time.Time   `json:"started_at"`
	CompletedAt OptDateTime `json:"completed_at"`
	Progress    OptProgress `json:"progress"`
	Links       ScanLinks   `json:"links"`
	Findings    []Finding   `json:"findings"`
	Grade       OptString   `json:"grade"`
	Score       OptInt      `json:"score"`
	Error       OptString   `json:"error"`
}

// GetID returns the value of ID.
func (s *Scan) GetID() uuid.UUID {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *Scan) GetStatus() ScanStatus {
	return s.Status
}

// GetTarget returns the value of Target.
func (s *Scan) GetTarget() string {
	return s.Target
}

// GetStartedAt returns the value of StartedAt.
func (s *Scan) GetStartedAt() time.Time {
	return s.StartedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *Scan) GetCompletedAt() OptDateTime {
	return s.CompletedAt
}

// GetProgress returns the value of Progress.
func (s *Scan) GetProgress() OptProgress {
	return s.Progress
}

// GetLinks returns the value of Links.
func (s *Scan) GetLinks() ScanLinks {
	return s.Links
}

// GetFindings returns the value of Findings.
func (s *Scan) GetFindings() []Finding {
	return s.Findings
}

// GetGrade returns the value of Grade.
func (s *Scan) GetGrade() OptString {
	return s.Grade
}

// GetScore returns the value of Score.
func (s *Scan) GetScore() OptInt {
	return s.Score
}

// GetError returns the value of Error.
func (s *Scan) GetError() OptString {
	return s.Error
}

// SetID sets the value of ID.
func (s *Scan) SetID(val uuid.UUID) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *Scan) SetStatus(val ScanStatus) {
	s.Status = val
}

// SetTarget sets the value of Target.
func (s *Scan) SetTarget(val string) {
	s.Target = val
}

// SetStartedAt sets the value of StartedAt.
func (s *Scan) SetStartedAt(val time.Time) {
	s.StartedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *Scan) SetCompletedAt(val OptDateTime) {
	s.CompletedAt = val
}

// SetProgress sets the value of Progress.
func (s *Scan) SetProgress(val OptProgress) {
	s.Progress = val
}

// SetLinks sets the value of Links.
func (s *Scan) SetLinks(val ScanLinks) {
	s.Links = val
}

// SetFindings sets the value of Findings.
func (s *Scan) SetFindings(val []Finding) {
	s.Findings = val
}

// SetGrade sets the value of Grade.
func (s *Scan) SetGrade(val OptString) {
	s.Grade = val
}

// SetScore sets the value of Score.
func (s *Scan) SetScore(val OptInt) {
	s.Score = val
}

// SetError sets the value of Error.
func (s *Scan) SetError(val OptString) {
	s.Error = val
}

func (*Scan) getScanRes() {}

// Ref: #/components/schemas/ScanCreated
type ScanCreated struct {
	ID     uuid.UUID  `json:"id"`
	Status ScanStatus `json:"status"`
	Target string     `json:"target"`
	// Set only when options.private=true (returned once).
	PrivateToken OptString `json:"private_token"`
	Links        ScanLinks `json:"links"`
}

// GetID returns the value of ID.
func (s *ScanCreated) GetID() uuid.UUID {
	return s.ID
}

// GetStatus returns the value of Status.
func (s *ScanCreated) GetStatus() ScanStatus {
	return s.Status
}

// GetTarget returns the value of Target.
func (s *ScanCreated) GetTarget() string {
	return s.Target
}

// GetPrivateToken returns the value of PrivateToken.
func (s *ScanCreated) GetPrivateToken() OptString {
	return s.PrivateToken
}

// GetLinks returns the value of Links.
func (s *ScanCreated) GetLinks() ScanLinks {
	return s.Links
}

// SetID sets the value of ID.
func (s *ScanCreated) SetID(val uuid.UUID) {
	s.ID = val
}

// SetStatus sets the value of Status.
func (s *ScanCreated) SetStatus(val ScanStatus) {
	s.Status = val
}

// SetTarget sets the value of Target.
func (s *ScanCreated) SetTarget(val string) {
	s.Target = val
}

// SetPrivateToken sets the value of PrivateToken.
func (s *ScanCreated) SetPrivateToken(val OptString) {
	s.PrivateToken = val
}

// SetLinks sets the value of Links.
func (s *ScanCreated) SetLinks(val ScanLinks) {
	s.Links = val
}

// ScanCreatedHeaders wraps ScanCreated with response headers.
type ScanCreatedHeaders struct {
	Location   OptString
	RetryAfter OptInt
	Response   ScanCreated
}

// GetLocation returns the value of Location.
func (s *ScanCreatedHeaders) GetLocation() OptString {
	return s.Location
}

// GetRetryAfter returns the value of RetryAfter.
func (s *ScanCreatedHeaders) GetRetryAfter() OptInt {
	return s.RetryAfter
}

// GetResponse returns the value of Response.
func (s *ScanCreatedHeaders) GetResponse() ScanCreated {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *ScanCreatedHeaders) SetLocation(val OptString) {
	s.Location = val
}

// SetRetryAfter sets the value of RetryAfter.
func (s *ScanCreatedHeaders) SetRetryAfter(val OptInt) {
	s.RetryAfter = val
}

// SetResponse sets the value of Response.
func (s *ScanCreatedHeaders) SetResponse(val ScanCreated) {
	s.Response = val
}

func (*ScanCreatedHeaders) createScanRes() {}

// Ref: #/components/schemas/ScanLinks
type ScanLinks struct {
	Self     string    `json:"self"`
	Events   OptString `json:"events"`
	Markdown OptString `json:"markdown"`
	Sarif    OptString `json:"sarif"`
}

// GetSelf returns the value of Self.
func (s *ScanLinks) GetSelf() string {
	return s.Self
}

// GetEvents returns the value of Events.
func (s *ScanLinks) GetEvents() OptString {
	return s.Events
}

// GetMarkdown returns the value of Markdown.
func (s *ScanLinks) GetMarkdown() OptString {
	return s.Markdown
}

// GetSarif returns the value of Sarif.
func (s *ScanLinks) GetSarif() OptString {
	return s.Sarif
}

// SetSelf sets the value of Self.
func (s *ScanLinks) SetSelf(val string) {
	s.Self = val
}

// SetEvents sets the value of Events.
func (s *ScanLinks) SetEvents(val OptString) {
	s.Events = val
}

// SetMarkdown sets the value of Markdown.
func (s *ScanLinks) SetMarkdown(val OptString) {
	s.Markdown = val
}

// SetSarif sets the value of Sarif.
func (s *ScanLinks) SetSarif(val OptString) {
	s.Sarif = val
}

// Ref: #/components/schemas/ScanOptions
type ScanOptions struct {
	SkipCategories []string `json:"skip_categories"`
	Private        OptBool  `json:"private"`
	WaitSeconds    OptInt   `json:"wait_seconds"`
}

// GetSkipCategories returns the value of SkipCategories.
func (s *ScanOptions) GetSkipCategories() []string {
	return s.SkipCategories
}

// GetPrivate returns the value of Private.
func (s *ScanOptions) GetPrivate() OptBool {
	return s.Private
}

// GetWaitSeconds returns the value of WaitSeconds.
func (s *ScanOptions) GetWaitSeconds() OptInt {
	return s.WaitSeconds
}

// SetSkipCategories sets the value of SkipCategories.
func (s *ScanOptions) SetSkipCategories(val []string) {
	s.SkipCategories = val
}

// SetPrivate sets the value of Private.
func (s *ScanOptions) SetPrivate(val OptBool) {
	s.Private = val
}

// SetWaitSeconds sets the value of WaitSeconds.
func (s *ScanOptions) SetWaitSeconds(val OptInt) {
	s.WaitSeconds = val
}

// Ref: #/components/schemas/ScanRequest
type ScanRequest struct {
	Target  string         `json:"target"`
	Options OptScanOptions `json:"options"`
}

// GetTarget returns the value of Target.
func (s *ScanRequest) GetTarget() string {
	return s.Target
}

// GetOptions returns the value of Options.
func (s *ScanRequest) GetOptions() OptScanOptions {
	return s.Options
}

// SetTarget sets the value of Target.
func (s *ScanRequest) SetTarget(val string) {
	s.Target = val
}

// SetOptions sets the value of Options.
func (s *ScanRequest) SetOptions(val OptScanOptions) {
	s.Options = val
}

// Ref: #/components/schemas/ScanStatus
type ScanStatus string

const (
	ScanStatusQueued    ScanStatus = "queued"
	ScanStatusRunning   ScanStatus = "running"
	ScanStatusCompleted ScanStatus = "completed"
	ScanStatusFailed    ScanStatus = "failed"
)

// AllValues returns all ScanStatus values.
func (ScanStatus) AllValues() []ScanStatus {
	return []ScanStatus{
		ScanStatusQueued,
		ScanStatusRunning,
		ScanStatusCompleted,
		ScanStatusFailed,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ScanStatus) MarshalText() ([]byte, error) {
	switch s {
	case ScanStatusQueued:
		return []byte(s), nil
	case ScanStatusRunning:
		return []byte(s), nil
	case ScanStatusCompleted:
		return []byte(s), nil
	case ScanStatusFailed:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ScanStatus) UnmarshalText(data []byte) error {
	switch ScanStatus(data) {
	case ScanStatusQueued:
		*s = ScanStatusQueued
		return nil
	case ScanStatusRunning:
		*s = ScanStatusRunning
		return nil
	case ScanStatusCompleted:
		*s = ScanStatusCompleted
		return nil
	case ScanStatusFailed:
		*s = ScanStatusFailed
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Severity
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

// AllValues returns all Severity values.
func (Severity) AllValues() []Severity {
	return []Severity{
		SeverityInfo,
		SeverityLow,
		SeverityMedium,
		SeverityHigh,
		SeverityCritical,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Severity) MarshalText() ([]byte, error) {
	switch s {
	case SeverityInfo:
		return []byte(s), nil
	case SeverityLow:
		return []byte(s), nil
	case SeverityMedium:
		return []byte(s), nil
	case SeverityHigh:
		return []byte(s), nil
	case SeverityCritical:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Severity) UnmarshalText(data []byte) error {
	switch Severity(data) {
	case SeverityInfo:
		*s = SeverityInfo
		return nil
	case SeverityLow:
		*s = SeverityLow
		return nil
	case SeverityMedium:
		*s = SeverityMedium
		return nil
	case SeverityHigh:
		*s = SeverityHigh
		return nil
	case SeverityCritical:
		*s = SeverityCritical
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Version
type Version struct {
	Version   string `json:"version"`
	Commit    string `json:"commit"`
	BuildDate string `json:"build_date"`
}

// GetVersion returns the value of Version.
func (s *Version) GetVersion() string {
	return s.Version
}

// GetCommit returns the value of Commit.
func (s *Version) GetCommit() string {
	return s.Commit
}

// GetBuildDate returns the value of BuildDate.
func (s *Version) GetBuildDate() string {
	return s.BuildDate
}

// SetVersion sets the value of Version.
func (s *Version) SetVersion(val string) {
	s.Version = val
}

// SetCommit sets the value of Commit.
func (s *Version) SetCommit(val string) {
	s.Commit = val
}

// SetBuildDate sets the value of BuildDate.
func (s *Version) SetBuildDate(val string) {
	s.BuildDate = val
}
